def empre_min(nom_em,sitio_em,des_em,año_em,idu_em,num_em):
    x=min(num_em)
    i=num_em.index(x)
    print(f'Empresa con menor # de empleados es: ')
    print(f'-Empresa: {nom_em[i]} ')
    print(f'-Website: {sitio_em[i]}')
    print(f'-Descrición: {des_em[i]}' )
    print(f'-Fundación: {año_em[i]} ')
    print(f'-Industria: {idu_em[i]} ')
    print(f'-#Empleados: {num_em[i]} \n')